### PR TITLE
transition button styles and add :active button style

### PR DESCRIPTION
**Pull request by ProMcTagonist**
a little smoother

### CODE REVIEW

**Comment by installgen2** [comment]
I don't think this is working correctly on chrom(e|ium)

**Comment by ProMcTagonist** [comment]
What's wrong? Tested it in Chromium before pushing.

**Comment by installgen2** [comment]
Well uhh, nothing happens

**Comment by ProMcTagonist** [comment]
https://d.maxfile.ro/ojvjinqydy.mkv

Chromium from debian testing

**Comment by installgen2** [comment]
Using Chromium on Fedora, clicking dindu nuffin

**Comment by ProMcTagonist** [comment]
Works in Google Chrome straight from the botnet as well. Dunno what to tell you.

**Comment by installgen2** [comment]
Ah fuck it

**Pull request merged**
