### PR TITLE
Friendly style

### PR DESCRIPTION
**Pull request by ProMcTagonist**
Nicer colors, hover colors on buttons, shortened the first section a bit

### CODE REVIEW

**Comment by installgen2** [comment]
I don't like the max-height changes, the navbar changes, or the font changes, the rest is alright.

**Comment by ProMcTagonist** [comment]
The first section is way too big and blank. We should be showing people the screenshot.

**Comment by installgen2** [comment]
Especially with the coloured navbar, it makes the cover look extremely broken, at least on devices with my screen size.

**Comment by ProMcTagonist** [comment]
Screenshot please?

**Comment by installgen2** [comment]
pic

**Comment by installgen2** [comment]
If you either change the navbar to match the cover, or change the max-height back, then I'm fine with it

**Comment by ProMcTagonist** [comment]
Max height is back to 800.

**Pull request merged**
